/* Generated by MyraPad at 9/15/2023 7:25:31 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace DdsKtxXna.Viewer.UI
{
	partial class MainForm: VerticalStackPanel
	{
		private void BuildUI()
		{
			_textBoxPath = new TextBox();
			_textBoxPath.Readonly = true;
			_textBoxPath.Id = "_textBoxPath";

			_buttonBrowse = new TextButton();
			_buttonBrowse.Text = "Browse...";
			_buttonBrowse.Id = "_buttonBrowse";

			var listItem1 = new ListItem();
			listItem1.Text = "PositiveX";

			var listItem2 = new ListItem();
			listItem2.Text = "NegativeX";

			var listItem3 = new ListItem();
			listItem3.Text = "PositiveY";

			var listItem4 = new ListItem();
			listItem4.Text = "NegativeY";

			var listItem5 = new ListItem();
			listItem5.Text = "PositiveZ";

			var listItem6 = new ListItem();
			listItem6.Text = "NegativeX";

			_comboCubePlane = new ComboBox();
			_comboCubePlane.Id = "_comboCubePlane";
			_comboCubePlane.Items.Add(listItem1);
			_comboCubePlane.Items.Add(listItem2);
			_comboCubePlane.Items.Add(listItem3);
			_comboCubePlane.Items.Add(listItem4);
			_comboCubePlane.Items.Add(listItem5);
			_comboCubePlane.Items.Add(listItem6);

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			horizontalStackPanel1.Widgets.Add(_textBoxPath);
			horizontalStackPanel1.Widgets.Add(_buttonBrowse);
			horizontalStackPanel1.Widgets.Add(_comboCubePlane);

			_image = new Image();
			_image.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_image.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_image.Id = "_image";

			_labelType = new Label();
			_labelType.Text = "Type: 2D";
			_labelType.Id = "_labelType";

			_labelFormat = new Label();
			_labelFormat.Text = "Format: Color";
			_labelFormat.Id = "_labelFormat";

			_labelWidth = new Label();
			_labelWidth.Text = "Width: 1024";
			_labelWidth.Id = "_labelWidth";

			_labelHeight = new Label();
			_labelHeight.Text = "Height: 1024";
			_labelHeight.Id = "_labelHeight";

			_labelLevels = new Label();
			_labelLevels.Text = "Levels: 1";
			_labelLevels.Id = "_labelLevels";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			verticalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			verticalStackPanel1.Left = -8;
			verticalStackPanel1.Top = -8;
			verticalStackPanel1.Widgets.Add(_labelType);
			verticalStackPanel1.Widgets.Add(_labelFormat);
			verticalStackPanel1.Widgets.Add(_labelWidth);
			verticalStackPanel1.Widgets.Add(_labelHeight);
			verticalStackPanel1.Widgets.Add(_labelLevels);

			var panel1 = new Panel();
			panel1.Widgets.Add(_image);
			panel1.Widgets.Add(verticalStackPanel1);

			
			Spacing = 8;
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			Widgets.Add(horizontalStackPanel1);
			Widgets.Add(panel1);
		}

		
		public TextBox _textBoxPath;
		public TextButton _buttonBrowse;
		public ComboBox _comboCubePlane;
		public Image _image;
		public Label _labelType;
		public Label _labelFormat;
		public Label _labelWidth;
		public Label _labelHeight;
		public Label _labelLevels;
	}
}
